/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope;

// Precache all the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Handle SKIP_WAITING message
self.addEventListener('message', (event) => {
  // Dev-only logs to avoid noise in production
  // eslint-disable-next-line no-undef
  if (typeof self !== 'undefined' && (self as any).ENV !== 'production') console.log('SW received message:', event.data);
  if (event.data && event.data.type === 'SKIP_WAITING') {
    // eslint-disable-next-line no-undef
    if (typeof self !== 'undefined' && (self as any).ENV !== 'production') console.log('SW: Skipping waiting and claiming clients');
    self.skipWaiting();
    self.clients.claim();
  }
});

// Handle install event
self.addEventListener('install', () => {
  // eslint-disable-next-line no-undef
  if (typeof self !== 'undefined' && (self as any).ENV !== 'production') console.log('SW: Installing');
  // Don't skip waiting automatically - wait for message
});

// Handle activate event
self.addEventListener('activate', (event) => {
  // eslint-disable-next-line no-undef
  if (typeof self !== 'undefined' && (self as any).ENV !== 'production') console.log('SW: Activating');
  // Claim clients when activated
  event.waitUntil(self.clients.claim());
});

// Runtime caching strategies

// Cache static assets (images, CSS, JS)
registerRoute(
  /\.(?:png|jpg|jpeg|svg|css|js)$/,
  new CacheFirst({
    cacheName: 'assets-cache-v2',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// Cache Firebase Functions API calls
registerRoute(
  /^https:\/\/us-central1-easy-fantasy-.*\.cloudfunctions\.net\//,
  new NetworkFirst({
    cacheName: 'api-cache-v2',
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24, // 24 hours
      }),
    ],
  })
);

// Cache Firestore API calls
registerRoute(
  /^https:\/\/firestore\.googleapis\.com\//,
  new NetworkFirst({
    cacheName: 'firestore-cache-v2',
    networkTimeoutSeconds: 8,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 12, // 12 hours
      }),
    ],
  })
);

// Cache weekly schedule data
registerRoute(
  ({ request }) => {
    return request.url.includes('weeklySchedule') || 
           request.url.includes('schedule');
  },
  new StaleWhileRevalidate({
    cacheName: 'schedule-cache-v2',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 60 * 60 * 6, // 6 hours
      }),
    ],
  })
);

// Cache user leagues
// NOTE: Removed overly-broad 'leagues' path caching to avoid intercepting SPA navigations

// Cache lineup data
registerRoute(
  ({ request }) => {
    return request.url.includes('lineup') && 
           (request.url.includes('fetch') || request.url.includes('stored'));
  },
  new NetworkFirst({
    cacheName: 'lineup-cache-v2',
    networkTimeoutSeconds: 8,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 2, // 2 hours
      }),
    ],
  })
);

// Cache tips data
registerRoute(
  ({ request }) => {
    return request.url.includes('tips') || 
           request.url.includes('gameTips');
  },
  new NetworkFirst({
    cacheName: 'tips-cache-v2',
    networkTimeoutSeconds: 6,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 60 * 60 * 4, // 4 hours
      }),
    ],
  })
);

// App Shell-style routing: serve index.html for navigation requests
// Exclude common asset and API paths
const navigationHandler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(navigationHandler, {
  denylist: [
    /\\.(?:png|jpg|jpeg|svg|css|js|json|map)$/,
    /^\/assets\//,
    /^\/api\//,
    /^\/__\//,
  ],
});
registerRoute(navigationRoute);

// eslint-disable-next-line no-undef
if (typeof self !== 'undefined' && (self as any).ENV !== 'production') console.log('SW: Custom service worker loaded'); 